[package]
name = "borsh-fuzz"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"
publish = false

[[bin]]
name = "borsh-fuzz"
path = "src/main.rs"

[dependencies]
honggfuzz = "0.5"
borsh = { path = "../../borsh" }
